SELECT CAR_ID, CAR_TYPE, FLOOR(DAILY_FEE*30*(100-DISCOUNT_RATE)/100) AS FEE
FROM (
    SELECT *, 
    SUM(if(START_DATE > DATE('2022-11-30 23:59:59')
             OR END_DATE < DATE('2022-11-01 00:00:00'), 0, 1)) AS NOT_AVAILABLE
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
      JOIN CAR_RENTAL_COMPANY_CAR USING(CAR_ID)
      GROUP BY CAR_ID
      HAVING NOT_AVAILABLE=0)
      AS T1
      JOIN (SELECT * FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
          WHERE DURATION_TYPE = '30일 이상') AS T2 USING(CAR_TYPE)
HAVING FEE BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC