SELECT ANIMAL_ID, INS.ANIMAL_TYPE, INS.NAME
FROM ANIMAL_INS INS join ANIMAL_OUTS OUTS USING(ANIMAL_ID)
WHERE SEX_UPON_INTAKE LIKE 'Intact%' AND (
    SEX_UPON_OUTCOME LIKE 'Spayed%' OR SEX_UPON_OUTCOME LIKE 'Neutered%')
ORDER BY ANIMAL_ID