SELECT YEAR, MONTH, GENDER, COUNT(GENDER) AS USERS
FROM (SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, GENDER, USER_ID
      FROM ONLINE_SALE JOIN USER_INFO USING(USER_ID) 
      GROUP BY YEAR, MONTH, GENDER, USER_ID) AS T
WHERE GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER;