SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, 
COUNT(DISTINCT USER_ID) AS PUCHASED_USERS,
ROUND(COUNT(DISTINCT USER_ID)/TOTAL_2021, 1) AS PUCHASED_RATIO
FROM ONLINE_SALE SALE JOIN USER_INFO INFO USING(USER_ID) join (
    select count(*) as TOTAL_2021 from user_info where joined like '2021%') as t
WHERE JOINED LIKE '2021%'
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH;