WITH TRUCK_DC AS (
    SELECT *
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE='트럭'
)
SELECT HISTORY_ID, FLOOR(DAILY_FEE*(DATEDIFF(END_DATE, START_DATE)+1)*(
    100-(CASE
                WHEN DATEDIFF(END_DATE, START_DATE)+1 < 7 THEN 0
                WHEN DATEDIFF(END_DATE, START_DATE)+1 < 30 THEN (SELECT DISCOUNT_RATE FROM TRUCK_DC WHERE DURATION_TYPE LIKE '7일 이상')
                WHEN DATEDIFF(END_DATE, START_DATE)+1 < 90 THEN (SELECT DISCOUNT_RATE FROM TRUCK_DC WHERE DURATION_TYPE LIKE '30일 이상')
                ELSE (SELECT DISCOUNT_RATE FROM TRUCK_DC WHERE DURATION_TYPE LIKE '90일 이상')
         END
        )
)/100) AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY HIS 
JOIN CAR_RENTAL_COMPANY_CAR CAR USING(CAR_ID)
WHERE CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC;
