SELECT HISTORY_ID,
FLOOR(DAILY_FEE * (DATEDIFF(END_DATE, START_DATE)+1) * (100 - (
    CASE
        WHEN DATEDIFF(END_DATE, START_DATE)+1<7 THEN 0
        WHEN DATEDIFF(END_DATE, START_DATE)+1<30 THEN
            (SELECT DISCOUNT_RATE
                FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
                WHERE CAR_TYPE='트럭' AND DURATION_TYPE LIKE '7%')
        WHEN DATEDIFF(END_DATE, START_DATE)+1<90 THEN
            (SELECT DISCOUNT_RATE
                FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
                WHERE CAR_TYPE='트럭' AND DURATION_TYPE LIKE '30%')
        ELSE (SELECT DISCOUNT_RATE
                FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
                WHERE CAR_TYPE='트럭' AND DURATION_TYPE LIKE '90%')
    END
)) / 100 )
AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY JOIN CAR_RENTAL_COMPANY_CAR USING(CAR_ID)
WHERE CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC;