WITH RECURSIVE T AS (
    SELECT 0 AS HOUR, 0 AS COUNT
    UNION ALL
    SELECT HOUR+1, COUNT FROM T
    WHERE HOUR<23
)
SELECT *
FROM (SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT
    FROM ANIMAL_OUTS
    GROUP BY HOUR UNION SELECT * FROM T) AS T
GROUP BY HOUR
ORDER BY HOUR;