WITH FE AS (SELECT SUM(CODE) AS CODE
           FROM SKILLCODES
           GROUP BY CATEGORY
           HAVING CATEGORY='Front End')
SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS, FE
WHERE SKILL_CODE & FE.CODE > 0
ORDER BY ID