SELECT ID AS USER_ID, NICKNAME, TOTAL_SALES
FROM (SELECT WRITER_ID AS ID, SUM(PRICE) AS TOTAL_SALES
      FROM USED_GOODS_BOARD WHERE STATUS='DONE' GROUP BY ID) AS B 
JOIN (SELECT USER_ID AS ID, NICKNAME FROM USED_GOODS_USER) AS U USING(ID)
WHERE TOTAL_SALES>=700000
ORDER BY TOTAL_SALES