SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW JOIN MEMBER_PROFILE USING(MEMBER_ID)
WHERE MEMBER_ID IN (
    SELECT MEMBER_ID FROM (
        SELECT *, RANK() OVER(ORDER BY COUNT(MEMBER_ID) DESC) AS R
        FROM REST_REVIEW
        GROUP BY MEMBER_ID) AS temp
    WHERE R=1)
ORDER BY REVIEW_DATE, REVIEW_TEXT;