SELECT T1.TITLE, T2.BOARD_ID, T2.REPLY_ID, T2.WRITER_ID, T2.CONTENTS,
DATE_FORMAT(T2.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD T1 
JOIN USED_GOODS_REPLY T2 ON T1.BOARD_ID = T2.BOARD_ID
WHERE T1.CREATED_DATE >= '2022-10-01' AND T1.CREATED_DATE < '2022-11-01'
ORDER BY T2.CREATED_DATE, T1.TITLE;
